
# Raised when an attempt is made to modify a frozen class.
class FrozenDotWizError(AttributeError): ...


def __getitem_impl__(self: NotDotWiz, _item) -> NotDotWiz: ...

def __setitem_impl__(_self: NotDotWiz, key, _value=None): ...

def __update_impl__(self: NotDotWiz, *_args, **_kwargs): ...


NOT_DOT_WIZ: NotDotWiz


class NotDotWiz:

    def __bool__(self) -> bool: ...
    def __getattr__(self, item: str) -> NotDotWiz: ...
    def __getitem__(self, item) -> NotDotWiz: ...
    def __repr__(self) -> str: ...

    __setitem__ = __setattr__ = setdefault = __setitem_impl__
    update = __update_impl__
